version: '3.5'
services:
        nginx-proxy:
                image: jwilder/nginx-proxy
                labels:
                        - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
                container_name: nginx-proxy
                restart: unless-stopped
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - html:/usr/share/nginx/html
                        - dhparam:/etc/nginx/dhparam
                        - vhost:/etc/nginx/vhost.d
                        - certs:/etc/nginx/certs:ro
                        - /var/run/docker.sock:/tmp/docker.sock:ro
                          
        nginx-letsencrypt:
                image: jrcs/letsencrypt-nginx-proxy-companion
                container_name: nginx-letsencrypt
                restart: unless-stopped
                depends_on:
                        - "nginx-proxy"
                volumes:
                        - certs:/etc/nginx/certs:rw
                        - vhost:/etc/nginx/vhost.d
                        - html:/usr/share/nginx/html
                        - /var/run/docker.sock:/var/run/docker.sock:ro

        mailserver:
                image: analogic/poste.io # (from https://hub.docker.com)
                container_name: mailserver
                restart: unless-stopped
                ports:
                        - "25:25"
                        - "110:110"
                        - "143:143"
                        - "587:587"
                        - "993:993"
                        - "995:995"
                        - "4190:4190"
                environment:
                        - LETSENCRYPT_EMAIL=contacto@uhosting.cl
                        - LETSENCRYPT_HOST=mail.uhosting.cl
                        - VIRTUAL_HOST=mail.uhosting.cl
                        - HTTPS=OFF
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - /usr/nginx/html/.well-known:/opt/www/.well-know
                        - /user/mailserver:/data


volumes:
        certs:
        html:
        vhost:
        dhparam:



